Fetch response queue
holochain/kitsune2 pull request #63
Opened 2024-12-31 02:09 UTC by jost-s

Adds a simple response queue to the fetch module which processes fetch requests one by one by loading requested ops from an op store and sends the available ops to the requester.

2025-01-03 02:06 UTC, jost-s commented on crates/api/proto/fetch.proto
> +  repeated kitsune2.op_store.Op data = 1;
Re-use op definition.

2025-01-03 02:09 UTC, jost-s commented on crates/api/src/fetch.rs
> +pub fn serialize_ops(value: Vec<MetaOp>) -> bytes::Bytes {
Very similar to the previous op id one. I could write this as a generic function which saves us code here but requires then types when calling the function.

2025-01-03 02:10 UTC, jost-s commented on crates/core/src/factories/core_fetch/back_off.rs
> -
These tests are just moved to the `request_queue.rs` file.

2025-01-03 02:12 UTC, jost-s commented on crates/core/src/factories/core_fetch/test.rs
This file contains now shared util functions. Tests for the parts of the fetch module are split out into their own test files.

2025-01-03 02:12 UTC, jost-s commented on crates/core/src/factories/core_fetch/test/request_queue.rs
No new test cases here, just updated API.

2025-01-03 15:41 UTC, ThetaSinner reviewed
Looking good, I like the approach and most of my comments are about naming and testing.

2025-01-03 15:41 UTC, ThetaSinner commented on crates/api/proto/op_store.proto
> +    bytes op_id = 1;
Want to question the value of sending the `op_id` with the `Op`. When we're communicating a diff, we have to work in terms of `op_id`s but when we have the `op_data`, we shouldn't trust the `op_id` that's been provided, we should calculate it from the `op_data`. This links to what we were discussing on the DHT diff PR where hash length mismatches would cause an error, we need to be properly checking these as they arrive.

2025-01-03 15:41 UTC, ThetaSinner commented on crates/api/src/op_store.rs
> +    fn read_ops(
The DHT diff PR defines `retrieve_ops`, we'll have to resolve these two

2025-01-03 15:41 UTC, ThetaSinner commented on crates/core/src/factories/core_fetch.rs
> +//! - Requests for data that the remote doesn't hold should be logged.
This looks like it needs a second look? Is this "requests for data we don't have are logged"?

2025-01-03 15:41 UTC, ThetaSinner commented on crates/core/src/factories/core_fetch.rs
> +//! - If sending or reception fails, it's the caller's responsibility to request again.
```suggestion
//! - If sending or receiving fails, it's the caller's responsibility to request again.
```

2025-01-03 15:41 UTC, ThetaSinner commented on crates/core/src/factories/core_fetch.rs
> +                None => continue,
A comment here might be nice, I think it's pretty clear but something like the one below for the `is_empty` check would be good

2025-01-03 15:41 UTC, ThetaSinner commented on crates/core/src/factories/core_fetch/back_off.rs
> +    pub state: HashMap<AgentId, BackOff>,
Is this really `pub` or `pub(crate)`?

2025-01-03 15:41 UTC, ThetaSinner commented on crates/core/src/factories/core_fetch/test/response_queue.rs
> +impl Transport for MockTransport {
Would mockall be appropriate here? Given we just want to work with one method on the type

2025-01-03 15:41 UTC, ThetaSinner commented on crates/core/src/factories/core_fetch/test/response_queue.rs
> +        fetch.respond_with_ops(requested_ops_1, agent_id_1.clone()),
I wonder if `request_op_data` might be a clearer name for this? I can't quite get this into my head

2025-01-03 15:41 UTC, ThetaSinner commented on crates/core/src/factories/core_fetch/test/response_queue.rs
> +async fn no_response_sent_when_no_ops_found() {
Possible to also test agent info not in peer store?

2025-01-03 15:41 UTC, ThetaSinner commented on crates/core/src/factories/core_fetch/test/response_queue.rs
> +async fn no_response_sent_when_no_ops_found() {
and also it'd be great to test error, and then queuing the request again for success. Just to demonstrate that there's no state preventing that working?

2025-01-03 17:28 UTC, jost-s commented on crates/api/src/op_store.rs
> +    fn read_ops(
resolved

2025-01-03 17:30 UTC, jost-s commented on crates/core/src/factories/core_fetch/back_off.rs
> +    pub state: HashMap<AgentId, BackOff>,
I think it makes no difference because the module `back_off` is not `pub`.

2025-01-03 17:31 UTC, jost-s commented on crates/core/src/factories/core_fetch/test/response_queue.rs
> +impl Transport for MockTransport {
Yes, for sure, I introduced mockall in the other PR and wanted to adapt the existing tests in another PR. But I can do it here already too.

2025-01-03 17:33 UTC, jost-s commented on crates/core/src/factories/core_fetch/test/response_queue.rs
> +        fetch.respond_with_ops(requested_ops_1, agent_id_1.clone()),
I don't find the name very comprehensible either. But it's not a request, it's a response to a request which pulls ops from the store and sends them to the requesting agent.

2025-01-03 17:35 UTC, jost-s commented on crates/api/proto/op_store.proto
> +    bytes op_id = 1;
That's true. I'll refactor.

2025-01-03 18:01 UTC, jost-s commented on crates/api/proto/op_store.proto
> +    bytes op_id = 1;
Wait, we don't have a hashing for that yet tho. Should I add some temporary hashing for the id?

2025-01-03 18:06 UTC, ThetaSinner commented on crates/api/proto/op_store.proto
> +    bytes op_id = 1;
Yes please. I had to do something similar with receiving ops into the store vs notifying the DHT model that ops have arrived on the host. Maybe it needs to be a proper test utility as part of demonstrating the host. I can't remember exactly where I did this because it's been a couple of weeks, but I think I skipped actually calculating hashes.

2025-01-03 18:06 UTC, ThetaSinner commented on crates/core/src/factories/core_fetch/back_off.rs
> +    pub state: HashMap<AgentId, BackOff>,
I guess so yes, I just prefer to be as restrictive as possible :)

2025-01-03 18:07 UTC, ThetaSinner commented on crates/core/src/factories/core_fetch/test/response_queue.rs
> +impl Transport for MockTransport {
No problem if mockall is coming elsewhere. It can be added here later if it's a pain to mix that between PRs

2025-01-03 18:10 UTC, ThetaSinner commented on crates/core/src/factories/core_fetch/test/response_queue.rs
> +        fetch.respond_with_ops(requested_ops_1, agent_id_1.clone()),
I see what you're saying but in my head it kind of is a request. We're choosing to queue the work in the implementation and this doesn't actually respond in the function return but it is still a remote peer requesting us to do work... Naming is hard :) 

Maybe something like `handle_op_data_request`?

2025-01-03 22:18 UTC, jost-s commented on crates/core/src/factories/core_fetch/test/response_queue.rs
> +        fetch.respond_with_ops(requested_ops_1, agent_id_1.clone()),
Yes, that's good and fits the `handle_incoming_ops` in the next PR. I'll change it to `handle_op_request`. I'd change `add_ops` to `request_ops` too.

2025-01-03 23:41 UTC, jost-s commented on crates/core/src/factories/core_fetch/back_off.rs
> +    pub state: HashMap<AgentId, BackOff>,
Okay, restrictive works for me.

2025-01-04 02:09 UTC, jost-s commented on crates/api/proto/op_store.proto
> +    bytes op_id = 1;
I'll have to compute hashes if the ops that are requested by id and then sent without id need to be compared. I can add that as a test utility.

2025-01-04 22:32 UTC, jost-s commented on crates/core/src/factories/core_fetch/test/response_queue.rs
> +impl Transport for MockTransport {
I added it now after all.

2025-01-04 22:34 UTC, jost-s commented on crates/core/src/factories/core_fetch/test/response_queue.rs
> +async fn no_response_sent_when_no_ops_found() {
Sure, tested those two aspects https://github.com/holochain/kitsune2/pull/63/commits/a3ee21fd8b6547405a5cbdf5ae4ca34282e84b3e

(Look at the commit while I haven't rewritten git history yet ;-)

2025-01-04 22:34 UTC, jost-s commented on crates/core/src/factories/core_fetch/back_off.rs
> +    pub state: HashMap<AgentId, BackOff>,
Restricted the hell out of it.

2025-01-04 22:36 UTC, jost-s commented on crates/api/proto/op_store.proto
> +    bytes op_id = 1;
I added it for this test only so far. The hash function will sooner or later be added globally. We can refactor this then to use it.

2025-01-04 22:36 UTC, jost-s commented on crates/core/src/factories/core_fetch.rs
> +//! - Requests for data that the remote doesn't hold should be logged.
Yes, looked twice now.

2025-01-04 22:36 UTC, jost-s commented on crates/core/src/factories/core_fetch.rs
> +//! - If sending or reception fails, it's the caller's responsibility to request again.
Applied

2025-01-07 11:09 UTC, ThetaSinner commented on crates/api/src/fetch.rs
> +    fn handle_op_request(
Nice, I like the naming now. It's clear these are a pair

2025-01-07 11:16 UTC, ThetaSinner commented on crates/core/src/factories/core_fetch/test/request_queue.rs
> +}
These tests don't seem to be using the mockall'd transport, is that intentional?

2025-01-07 11:24 UTC, ThetaSinner commented on crates/core/src/factories/core_fetch/test/response_queue.rs
> +    mock_transport.expect_send_module().returning({
This is nice, just mocking what you need to mock for the test

2025-01-07 11:25 UTC, ThetaSinner approved these changes
Looking great, just needs a rebase :)

2025-01-07 16:25 UTC, neonphog commented on Cargo.toml
> +mockall = "0.13"
move down to dev dependencies?

2025-01-07 16:26 UTC, neonphog commented on crates/api/Cargo.toml
> +mockall = { workspace = true }
move down to dev dependencies?

2025-01-07 16:32 UTC, neonphog commented on crates/api/src/fetch.rs
> +    bytes::Bytes::copy_from_slice(&ops)
This writes the data, and then copies it again. See: https://github.com/holochain/kitsune2/blob/9cd2ec666f66ebc90d71b445abd612002884e034/crates/api/src/protocol.rs#L15-L24

2025-01-07 16:35 UTC, neonphog commented on crates/api/src/transport.rs
> +#[automock]
```suggestion
#[cfg_attr(any(test, feature = "test_utils"), automock)]
```

?

2025-01-07 16:35 UTC, neonphog commented on crates/core/Cargo.toml
> +sha2 = "0.10.8"
move to workspace

2025-01-07 16:39 UTC, neonphog commented on crates/api/Cargo.toml
> +mockall = { workspace = true }
Alas, if this is needing to be exported it cannot go in dev-dependencies : ( -- but at the very least it should be optional and only enabled with a test_utils feature, right?

2025-01-07 16:47 UTC, neonphog commented on crates/api/src/fetch.rs
> +    fn handle_op_request(
This should not be in the external api.

1. In fetch module constructor--register with transport module to receive module messages.
2. When we receive a request, send that request to the response queue.
3. The request will come with a URL, so you don't need to look up by agent id... just send it to where we got the request from.

2025-01-07 16:49 UTC, neonphog commented on crates/api/src/fetch.rs
> +    fn handle_op_request(
Of course, the concrete implementation can have this function be private that you can call for testing to bypass actually receiving things in the transport.

2025-01-07 16:50 UTC, neonphog requested changes
Some suggestions re efficiency and dependencies, but mostly the module api: https://github.com/holochain/kitsune2/pull/63#discussion_r1905770150

Otherwise, this looks awesome!

2025-01-07 18:22 UTC, jost-s commented on crates/api/src/fetch.rs
> +    bytes::Bytes::copy_from_slice(&ops)
Cool, I'll do that. Question about that protocol code, should that not panic when encoding fails?

2025-01-07 19:31 UTC, neonphog commented on crates/api/src/fetch.rs
> +    bytes::Bytes::copy_from_slice(&ops)
Indeed. Probably the only way it could error is memory allocation. Up to you : )

2025-01-07 21:21 UTC, jost-s commented on crates/api/src/fetch.rs
> +    fn handle_op_request(
`recv_module_msg` is sync, the response queue sender is async - use a tokio task for that?

2025-01-07 21:29 UTC, neonphog commented on crates/api/src/fetch.rs
> +    fn handle_op_request(
The pattern we've started to establish (but should evaluate if appropriate on a case-by-case basis) is to use a bounded channel, then [try_send](https://docs.rs/async-channel/2.3.1/async_channel/struct.Sender.html#method.try_send) and if the send fails, it means the system is overloaded, so log the problem and drop the request.

It seems like that is appropriate here.

2025-01-07 21:32 UTC, jost-s commented on crates/api/src/fetch.rs
> +    fn handle_op_request(
Great.

2025-01-08 02:16 UTC, jost-s commented on crates/api/src/transport.rs
> +#[automock]
Yes, applied. `all(test, feature = "test_utils")` doesn't work. Do you know why? I would think that automock only works in a test when `test_utils` is enabled.

2025-01-08 02:18 UTC, jost-s commented on crates/core/src/factories/core_fetch/test/response_queue.rs
> +async fn no_response_sent_when_no_ops_found() {
I've taken out the test for agent info in peer store, because the response is now sent directly to the incoming url.

2025-01-08 02:41 UTC, jost-s commented on crates/api/proto/fetch.proto
> +  repeated kitsune2.op_store.Op data = 1;
done https://github.com/holochain/kitsune2/pull/63/commits/48fdacbc3d74d86cfafefe7ce4575fda7592021f

2025-01-08 02:42 UTC, jost-s commented on crates/core/src/factories/core_fetch/test/request_queue.rs
> +}
done here https://github.com/holochain/kitsune2/pull/63/commits/6a3221aa87f0f42aee660813ad5588c4c942a7db

2025-01-08 02:42 UTC, jost-s commented on Cargo.toml
> +mockall = "0.13"
all the mockall feature gating https://github.com/holochain/kitsune2/pull/63/commits/d123d56c507e42f05e2088fa03d4da9c6b452e86

2025-01-08 02:43 UTC, jost-s commented on crates/api/src/fetch.rs
> +    bytes::Bytes::copy_from_slice(&ops)
done https://github.com/holochain/kitsune2/pull/63/commits/4659a4af7162553e50f00b809afa615f6e3010f0
and for op_id serialization https://github.com/holochain/kitsune2/pull/63/commits/3d7fb68e70738c8c1e8a5f53d9621a7bbbad5c76

2025-01-08 02:45 UTC, jost-s commented on crates/core/src/factories/core_fetch.rs
> +    response_handler: DynTxModuleHandler,
I'm not so happy with this, but somehow I need to send messages to the response queue. This seemed the simplest.

2025-01-08 02:46 UTC, jost-s commented on crates/core/src/factories/core_fetch.rs
> +        _module: String,
I don't know what to do with space and module here. For every space there'll be a fetch module instance, and this is a handler registered specifically for the fetch module, so what are these parameters for?

2025-01-08 13:00 UTC, ThetaSinner commented on crates/api/src/transport.rs
> +#[automock]
Do we want to use `test-utils` rather than `test_utils` this time? Or no preference?

2025-01-08 18:20 UTC, neonphog commented on crates/core/src/factories/core_fetch.rs
> +        _module: String,
Just in case you want to use the same callback for multiple spaces / modules. You can safely ignore them.

2025-01-08 18:28 UTC, neonphog commented on crates/core/src/factories/core_fetch.rs
> +}
pretty sure these all have default impls

```suggestion
impl TxBaseHandler for FetchResponseHandler {}
```

2025-01-08 18:30 UTC, neonphog commented on crates/core/src/factories/core_fetch.rs
> +    response_handler: DynTxModuleHandler,
meh, I'm fine with this : )

2025-01-08 18:36 UTC, neonphog commented on crates/api/src/transport.rs
> +#[automock]
I wish rust just never allowed dashes anywhere in filenames or features or anything... then everything could be underscores and we wouldn't have to worry about stuff like this : ) -- that being said, given the way things are already, I don't have a preference. Totally cool to switch this or not : )

2025-01-08 18:36 UTC, neonphog submitted a review, later dismissed
Sweet

2025-01-08 18:43 UTC, jost-s commented on crates/core/src/factories/core_fetch.rs
> +}
That hadn't occurred to me.

2025-01-08 18:46 UTC, jost-s commented on crates/api/src/transport.rs
> +#[automock]
I have no preference whatsoever, just for consistency. @ThetaSinner Are you suggesting using dashes in features?

2025-01-08 18:48 UTC, jost-s commented on crates/api/src/transport.rs
> +#[automock]
And would be great to know the answer to this https://github.com/holochain/kitsune2/pull/63#discussion_r1906250155.

2025-01-08 19:43 UTC, ThetaSinner submitted a review, later dismissed

2025-01-08 20:03 UTC, ThetaSinner commented on crates/api/src/transport.rs
> +#[automock]
> Yes, applied. all(test, feature = "test_utils") doesn't work. Do you know why? I would think that automock only works in a test when test_utils is enabled.

I'm not sure about this. it's not documented so I'd expect this to behave like any other attribute and be possible to conditionally enable. What happens?

2025-01-08 20:04 UTC, ThetaSinner commented on crates/api/src/transport.rs
> +#[automock]
Oh but shouldn't it be an "any"? So that it's enabled either on "test" or from another crate if "test_utils" is enabled?

2025-01-08 20:06 UTC, jost-s commented on crates/api/src/transport.rs
> +#[automock]
When I use `all` instead of `any` and then run `make test`, the mock imports cannot be found in the tests.

2025-01-08 20:14 UTC, jost-s commented on crates/api/src/transport.rs
> +#[automock]
Using the automock'd struct inside of `kitsune2_api` fails if run without feature `test_utils`.

2025-01-08 20:28 UTC, jost-s commented on crates/api/src/transport.rs
> +#[automock]
Here it gets wicked: With `all`, the test in `kitsune2_api` succeeds when run with `--features test-utils`. But the test in `kitsune2_core` only works with `any`.

2025-01-08 22:58 UTC, jost-s commented on crates/api/src/transport.rs
> +#[automock]
Mystery lifted: `#[cfg(test)]` is only active for unit tests of the crate where the tests are run. So `all(test, feature = "mockall")` will work for `kitsune2_api` if there were unit tests _and_ the feature is enabled when running the test. It will never work for tests outside of the crate, because `cfg(test)` is then inactive. That's why `any` must be used.

2025-01-08 22:59 UTC, jost-s commented
All tests enabled again an no longer flaky, it seems. Please approve again @neonphog.

2025-01-09 00:32 UTC, neonphog approved these changes

2025-01-09 00:32 UTC, merged